### PR TITLE
Update the filter example WORKSPACE to remove `repository` param.

### PR DESCRIPTION
**Pull request by jmillikin-stripe**
Also name the workspace something more accurate (`@envoy` is the main
repo).

### CODE REVIEW

**Comment by mattklein123** [comment]
Do you mind bumping submodule as well? Otherwise I don't think this will actually build?

**Comment by jmillikin-stripe** [comment]
> Do you mind bumping submodule as well? Otherwise I don't think this will actually build?

I don't know much about Git submodules, sorry -- could you tell me the command to do that?

There's an `envoy/` directory here, but it's got nothing in it.

**Comment by mattklein123** [comment]
```
mklein@localhost:~/Source/envoy-filter-example$ git submodule init
mklein@localhost:~/Source/envoy-filter-example$ git submodule update
Submodule path 'envoy': checked out '921bed8bab621d7e9979a219c939c6c9f665c08f'
mklein@localhost:~/Source/envoy-filter-example$ cd envoy
mklein@localhost:~/Source/envoy-filter-example/envoy$ git checkout master
Previous HEAD position was 921bed8... Move Router filter to V2 api (#1982)
Switched to branch 'master'
Your branch is behind 'origin/master' by 238 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
mklein@localhost:~/Source/envoy-filter-example/envoy$ cd ..
mklein@localhost:~/Source/envoy-filter-example$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   envoy (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
mklein@localhost:~/Source/envoy-filter-example$ git add .
mklein@localhost:~/Source/envoy-filter-example$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   envoy
```

**Comment by jmillikin-stripe** [comment]
OK, submodule updated.

**Pull request merged**
