### PR TITLE
bazel: re-add tools/bazel.rc.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
cc @htuch

**Comment by PiotrSikora** [comment]
@htuch you could, but then it would break with removal of `tools/bazel.rc` from Envoy's repo.

Keeping `.bazelrc` -> `envoy/.bazelrc` and `tools/bazel.rc` -> `envoy/tools/bazel.rc` means that `tools/bazel.rc` will eventually fall out of use (once everybody is using Bazel 0.19+) and can be removed without any coordination, i.e. deprecation of `tools/bazel.rc` will be handled completely within Envoy repo.

**Comment by lizan** [comment]
I think we should fix this in envoy side, symlink envoy/.bazelrc to envoy/tools/bazel.rc?

**Comment by PiotrSikora** [comment]
@lizan symlinking results in this bogus error, although it's most likely a bug in Bazel:
```
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/path/to/envoy/.bazelrc
```

**Comment by lizan** [comment]
@PiotrSikora was trying locally, if you apply following patch to Envoy it seems fine?

```
diff --git a/.bazelrc b/.bazelrc
deleted file mode 100644
index 416f1229..00000000
--- a/.bazelrc
+++ /dev/null
@@ -1 +0,0 @@
-import %workspace%/tools/bazel.rc
diff --git a/.bazelrc b/.bazelrc
new file mode 120000
index 00000000..f0b624fe
--- /dev/null
+++ b/.bazelrc
@@ -0,0 +1 @@
+tools/bazel.rc
\ No newline at end of file
```

**Comment by PiotrSikora** [comment]
@lizan are you testing with Bazel 0.19?

**Comment by lizan** [comment]
No, 0.18, will it break with 0.19?

**Comment by PiotrSikora** [comment]
@lizan it won't break, but it will result in the bogus message I pasted earlier. Let's see if this can be sorted out before final 0.19 release (see: https://github.com/bazelbuild/bazel/issues/6469).

**Comment by lizan** [comment]
Closing, we no longer need this.

**Pull request closed without merging**
